dev_mode:
  debugging: false
  toy_test: false

wandb:
  project_name: BADGER
  session_name: badger
  group_name:  pert

ddp:
  port: 22789

path:
  dataset: data
  checkpoint: checkpoint

dataprep:
  label_type: real 
  split_type: pert_id # cell_id, pair_id
  selection:  
 
  filter_qc: true
  filter_tas: 0.2

  use_pert_id: false
  use_pert_type: false
  use_cell_id: false
  use_pert_idose: false
  baseline_default: false

experiment:
  folds: 5
  fold_num: 0
  test_mode: false
  random_seed: 88
  dataset: badger # fixed
  analysis_mode: false
  train_subsample: false

model_params:
  pred_model: badger 
  gene_embed: gene2vec
  drug_embed: fragmentecfp
  cell_embed: similarity #
  hidden_dim: 128
  dropout_rate: 0.1

  chemberta:
    model_name: DeepChem/ChemBERTa-77M-MTR # seyonec/ChemBERTa-zinc-base-v1, DeepChem/ChemBERTa-77M-MLM

  badger:
    light_mode: False # If True, only xmab-gsab. Else, pathmab-signmab-gsab 
    plus_ultra: False # testing
    with_gsab:  True #  NEW!! THERE IS NO GENE-GENE SELF-ATTENTION BLOCK!!!!!!!!!! 
    drugcell_fusion: # leave it blank (default is early fusion)
    drug_pooled: True
    decoder_multiway: False # NEW!!! GENE-WISE PREDICTION? OR NOT?


    xmab: 
      num_heads: 2
      attn_option: additive
      same_linear: true
      norm_method: set_norm
      norm_affine: true 
      clean_path: true

    pathmab:
      num_heads: 2
      attn_option: additive
      same_linear: true
      norm_method: set_norm
      norm_affine: true
      clean_path: true
      path_embed: msig 

    signmab:
      num_heads: 2 
      attn_option: additive
      same_linear: true 
      norm_method: set_norm 
      norm_affine: true
      clean_path: true
      gene_embed: gene2vec

    gsab:
      model_name: #just leave it blank (it's sab)
      num_blocks: 1 # at least one 
      num_heads: 2
      attn_option: scaled_dot
      same_linear: true 
      norm_method: set_norm 
      norm_affine: true
      clean_path: true

      isab: #only for isab, will be deprecated
        num_ipoints: 100
      
      attn_supervised: none # diag, string_ppi_scale, ppi

    plusmab:
      model_name: #just leave it blank
      num_heads: 2
      attn_option: additive
      same_linear: true 
      norm_method: set_norm 
      norm_affine: true
      clean_path: true

  baseline_default: false

train_params:
  batch_size: 32 #512
  num_epochs: 100 # fix to 100!
  learning_rate: 0.0001 #0.00005
  weight_decay: 0.0
  loss_function: hybrid_cosine_mse

  point_wise_shrinkage:
    a_coef: 10
    c_coef: 0.2
  main_coef: 1.0
  badger:
    pathmab_coef: 0.05
    genesab_coef: 0.0
    gene_spreadout_coef: 0.0
  early_patience: 10 
  best_criteria_metric: dge/pos/ndcg
  baseline_default: false 

